name: spfx-build-deploy

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - "*"
    exclude:
      - az-pipelines/*
      - _images/*

variables:
  sppkg: spfx-devops.sppkg
  nodeVersion: "14.x"
  azSubs: scSPFx
  vault: spfxvault
  envflag: staging

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: Build
    displayName: Build and Provision

    jobs:
      - job: BuildJob
        displayName: Build SPFx
        steps:
          - template: templates/spfx-build.yaml
            parameters:
              nodeVersion: $(nodeVersion)
              pkg: $(sppkg)         

  - stage: Deploy
    displayName: Deploy to M365
    dependsOn: Build
    jobs:
      - deployment: DeployM365
        displayName: Deploy to M365
        environment: M365Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureKeyVault@1
                  displayName: 'Azure Key Vault: $(vault)'
                  inputs:
                    azureSubscription: '$(azSubs)'
                    KeyVaultName: '$(vault)-$(envflag)'

                - template: templates/spfx-deploy-cli.yaml
                  parameters:
                    nodeVersion: $(nodeVersion)
                    pkg: $(sppkg)
                    username: $(username)
                    password: $(password)