name: teams-ci

trigger: none
pr: none

pool:
  vmImage: "ubuntu-20.04"     

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: "ubuntu-20.04"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 16.x
            displayName: Use Node 16.x
          - task: CmdLine@2
            displayName: npm install
            inputs:
              script: "npm install"

          - task: gulp@1
            displayName: "gulp bundel"
            inputs:
              gulpFile: "gulpfile.js"
              targets: "bundle"
              arguments: "--ship"
              enableCodeCoverage: false

          - task: gulp@1
            displayName: "gulp package solution"
            inputs:
              gulpFile: "gulpfile.js"
              targets: "package-solution"
              arguments: "--ship"

          - task: CopyFiles@2
            displayName: "Copy Files to: $(Build.ArtifactStagingDirectory)/spfxdrop"
            inputs:
              Contents: "sharepoint/solution/*.sppkg"
              TargetFolder: "$(Build.ArtifactStagingDirectory)/spfxdrop"

          - task: PublishBuildArtifacts@1
            displayName: "Publish artifacts: spfxdrop"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/spfxdrop"